### ISSUE TITLE
В Update_All использовать foreach для обновления здоровья игроков

### ISSUE THREAD

**Issue by petelind** [EcoLife-cs501/KnightVSSkeleton#3]
1. На форме MainForm есть коллекция allGameObjects типа Fighter
2. В нее добавлены и скелет, и рыцарь, которых мы трактуем как Fighter. (skeleton as Fighter)
3. При вызове Update_All() foreach циклом проходится по каждому объекту в allGameObjects и вызывает его собственный метод обновления здоровья.

**Comment by petelind** [comment]
Отлично! :+1:
Для того, чтобы добавить объекты в коллекцию, тебе придется upcast их.

**Comment by HostSpirit** [comment]
Привет! Ничего не писал или ничего не пушил? :hammer_and_wrench:

**Comment by petelind** [comment]
Тех кто долго не делал pull & push ждет большой сюрприз - им предстоит merge conflict и его разрешение 😈
